language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: grCgDmYpTeTm5kE8/avZj8OU60yqufLsLfOsT3GLwRJRwW5Fk1lkLEvSrewe/8gikxkyj7fyViaxIaQcANjldAb56J7FTrlKwWfFnl43ntKYX4vRCoOT9dhi076QJysAhh+cXhmyR70AcQ27R3+4Fqf93Ei2YVRcBGXRxRh2cqMV9MwohMtYhdaiNVk4ay0zP1a6ISkQ8bLYm/Q32rrr+IifN0oHLII7jYct+bGZQW6l2Fg6uZnIa2mE/GVXQNmD/TqzeUQQCL7MR1psl/TnEaqH1CLYF+eysETvQwpuKtt1dqX7sTEmNIs4zGZEV2pYDVRsZgDR4CpEXikEC5Kk4GQfEVDdfqeKFZ0ZUVUaKqcF2/hSqHTnXzAmg5sSATkCwtUiEzBDikYNce5C4guQA0QeJI0hq1KMYWrFsGHxsPL9Kd9qaB1awn7QZhd1mQ55VWlqI4JRKKxB3s8+rwHVbPIeJIcdwBtikjUw2e41zyXWPXBtxOwLrO5WuaSE+ODMIqSD65dF6cL+VBznxAzLo+xD/Dha1cB4pvC40GBquElju+Nek8o421TSp7IGxH98vX37iXWeRWhvRJpiTTfp70bKdwdE29v6fO7gvW99j8h9e565+IHwd4gv7Nd/8uQ9NP169lVtpqyLRVQGXf58knsMGFOGTR3/jjChfF9u3pE=
  file:
    - "longest-streak.js"
    - "longest-streak.min.js"
  on:
    tags: true
    node: '9.0'
