language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XJdQFM8uRUNf7LBmJvyXJFiEsIynrwhABTyv85Y07DbNtW3wHdnVc5gbCiCmLAf/R9l4EJa3+cH6MV7d4dksEWwOL++WPhISVcU3mbrf4/YdjBdTHqACCvHRFSiLqMSW0TXePynmHkFjSg9XeqjKwFomQE2MLcHkd6kX/r6lt8vM3ekWBUHcYoRqVu2FxRMeqX06A0bwf7h423Zb8dO8y+WTsYXf2p70jPYUjOJFzIz6wIWs6KFUfwxSTkheogKpfII+O2LBb3JNiKPr0Te8VPxDf2W1lfAcx0GqZnkEVMjDExIUYjM5OP9XrzmQdrVKrzb28llP8jSKo0ZSpSXWw23UhLXtn2WgKUxXNA7kqtR2TN+T9yahjVgU/0McLpWRbrw6HoQ1ResnSQETl98yd5drnk5BgWRaxx9FI1T1UEJRXxPsp6ZKDtmclBQicwV5MWraBzn98ebmHxzZFK6kGZWFoBFVf0pM+PzRmA8TTgGrGt/GWpWM+uS+6l1xBHPgaKlBqHN+JzxWExIoKk/TCRL9SIHkSBg78nQZEKBUEZkeMfy8qopZt3XNcx7Qss3jp9uFuXYdjTbfCqYuc4r0U6KC+iNROGXHgq04/Dz1iN8Wj3SCZJQBiTkZwRvUU7zg81FCT5mrTsPQs+WeU3WrBA5v0cA5c7m45J7fh0ixNug=
  file:
    - 'longest-streak.js'
    - 'longest-streak.min.js'
  on:
    tags: true
