language: node_js
script: npm run-script test-travis
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
sudo: false
after_script: npm install coveralls@2.11.2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
